### ISSUE TITLE
There is No .mat  format file of gt in the BSDS-RINED test set

### ISSUE THREAD

**Issue by zhoujh2020** [MengyangPu/RINDNet#2]
Excuse me, when I retrained the network and planned to evaluate the prediction results, I found that there was no .mat format file of the test set, and the ground truth map of the test set only had a .png format file. I tried to generate the .mat file by myself from the .png file, but encountered some unknown errors during the evaluation. Can you please release the ground truth map in .mat format? Thank you very much for your help.

**Comment by MengyangPu** [comment]
Thanks, you can download the .mat format files [here](https://drive.google.com/file/d/1pLXJblrHMxy3p2c6ulSUSAG5AoV_KaC9/view?usp=sharing).

**Comment by ZhouZoey** [comment]
Sorry, can you send me the PNG format picture of the test data set?

**Comment by MengyangPu** [comment]
You can download the PNG format picture from [BaiDuNetdisk](https://pan.baidu.com/s/1UPIIqhZtQte4RO5WwcjqFg), (code:e7rg) or [GoogleDrive](https://drive.google.com/drive/folders/1W4bF2pMEa5g2Wc0qskr-GiotNx0XAbeX?usp=sharing)
